# Dependencies
markdown:            redcarpet
highlighter:         pygments

# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: true

# Setup
title:               prepsourced.com
tagline:             'Relevant Prepping Information'
description:         'Prepsourced.com - your weekly prepping digest.'
url:                 http://prepsourced.com
baseurl:             /
paginate:            5

# About/contact
author:
  name:              Craig Bensemann
  url:               http://twitter.com/CraigBensemann
  email:             craig.bensemann@gmail.com

# Custom vars
version:             1.0.0
